version: '3.1'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    expose:
      - "5434"
    ports:
      - "5434:5434"
    volumes:
      - db_data:/var/lib/postgresql/data 
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: -p 5434

  pricing:
    build: ./pricing/
    command: npm run start
    ports:
      - "3000:3000"
    depends_on:
      - db
    entrypoint: ["npm", "run", "start"]
    environment:
      POSTGRES_USER: ${POSTGRES_USER}       
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
  
volumes:
  db_data: 